### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by adamziel** [WordPress/php-toolkit#84]
## Blueprints library – version 0.1 for early adopters

- Feature completeness
	- wp-blueprints CLI tool to prove it works natively
		- Command to execute a Blueprint
		- Command to turn Blueprint into a Snapshot (.zip bundle)
	- Integrate into WordPress Playground to prove it works with WASM
		- Figure out the development workflow
		- Figure out the version update workflow
	- https://github.com/WordPress/blueprints-library/issues/87
	- Decide what to do when WordPress directory already exists – delete? Act on that WordPress instance?
- Distribution
	- CLI tool documentation
		- The default --help message
		- Web page with Quick start and usage examples
	- Build flow
		- Building a minified ~200kb .phar library to use in Playground
		- Building a CLI tool as .phar
	- Distribution
		- Scripts to publish GitHub releases
- Superior quality from day 1
	- [ ] [Exception handling when running steps](https://github.com/WordPress/blueprints-library/issues/27)
	- [ ] #108
	- [ ] Unit Tests
		- [ ] HTTP Client
		- [ ] All Blueprint steps
		- [ ] ZIP processing
		- [ ] Parsing and compiling for all input types: JSON string, stdClass and `Blueprint`
		- [ ] Blueprint Mapper
		- [ ] Blueprint Validator
	- [ ] Improve JSON Schema discriminator-related error messages
	- [ ] Code formatter setup (PHPCBF)
	- [ ] Contributor docs
		- Setting up the project
		- JSON Schema as the source of truth
		- Regenerating models classes
		- How to build the phar library with box ?
		- Why include dependencies in the repo? (PHP 7.0 - 8.3 compat, composer constraints issues)
	- [ ] Optional: static code analysis (PHPCS) for PHP 7.0 – 8.3 – PHPUnit solves a similar problem
	- [x] https://github.com/WordPress/blueprints-library/pull/86

## 1.0 Stable Release

- Research
	- [Settle on the Blueprint schema](https://github.com/WordPress/blueprints/issues/6)
	- Explore integration with wp-env
	- Explore [runtime adapters](https://github.com/WordPress/blueprints-library/issues/1)
- Other
	- Blueprint library consumer documentation – tutorials, examples, API reference
	- @php-wasm/cli support – there's a few functions to [wrap in Asyncify](https://github.com/WordPress/wordpress-playground/issues/251)
	- Downloads caching for both native PHP and PHP.wasm
	- Scripts to [publish composer packages](https://github.com/WordPress/blueprints-library/issues/3)
	- [Windows Compatibility](https://github.com/WordPress/blueprints-library/issues/60)

## 1.1 Extra features

- wp-cli plugin
- [Publish Composer Packages](https://github.com/WordPress/blueprints-library/issues/3)
- WordPress plugin (Integrate with the WordPress Playground plugin? Build a new one?)
- [Explore Custom Post Types handling in Blueprint](https://github.com/WordPress/blueprints-library/issues/32)

## Future – Path to WordPress Core

- Refactor to WordPress Coding Standards
- Integrate into WordPress core

cc @reimic

**Comment by reimic** [comment]
I need a bit of your guidance at #82 to fix some issues the e2e tests have uncovered and then I'll work at things mentioned in `Superior quality from day 1` in a semi-random fashion.
